#!/usr/bin/env ruby

require 'mockstarter'
require 'thor'

## CLI for Mockstarter. Takes input and creates objects to manipulate as the user wants.
## Some workarounds in here are string manipulation on to delete ids from usernames (i am catting them together in redis)

class MockStarterCLI < Thor
  desc "project PROJECTNAME GOAL", "create a project by PROJECTNAME for given GOAL"
  def project(projectname, goal)
    project = Mockstarter::Project.new(:projectname => projectname, :goal => goal, :redis =>  Redis.new(:url => ENV['MOCKSTARTER_BRAIN']))
    project.create
    say "Created new campaign #{projectname} with goal of $#{goal}!"
  end

  desc "back USERNAME PROJECTNAME CREDITCARD AMOUNT", "fund a project for USERNAME to PROJECTNAME with CREDITCARD for AMOUNT"
  def back(name, projectname, creditcard, amount)
    project = Mockstarter::Fund.new(:username => name, :projectname => projectname, :amount => amount, :creditcard => creditcard, :redis =>  Redis.new(:url => ENV['MOCKSTARTER_BRAIN']))
    project.transaction
    say "Backed #{projectname} with amount of $#{project.instance_variable_get(:@amount)}!"
  end

  desc "list PROJECTNAME", "show backers for PROJECTNAME"
  def list(projectname)
    project = Mockstarter::Project.new(:projectname => projectname, :redis =>  Redis.new(:url => ENV['MOCKSTARTER_BRAIN']))
    project.log.each {|e| puts "-- " + e.sub(/(:*[:0-9][^\s]+)/,"") + "\n"}
    if project.funded == true
      puts "#{projectname} is SUCCESSFUL!"
    elsif project.funded == false
      puts "#{projectname} doesn't exist. Create it!"
    else
      puts "#{projectname} needs $#{project.funded} more to be SUCCESSFUL"
    end
  end

  desc "backer USERNAME", "get projects backed by USERNAME"
  def backer(username)
    project = Mockstarter::Fund.new(:username => username, :redis =>  Redis.new(:url => ENV['MOCKSTARTER_BRAIN']))
    project.log.each {|e| puts "-- " + e.sub(/(:*[:0-9][^\s]+)/,"") + "\n"}
  end

end

## Ensure that the MOCKSTARTER_BRAIN environment variable is set before starting the CLI.
if ENV['MOCKSTARTER_BRAIN'].nil?
  raise ArgumentError, 'You must set MOCKSTARTER_BRAIN env variable to redis url'
end

MockStarterCLI.start(ARGV)
